# Generated by Django 6.0.6 on 2026-06-20 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("channel_title", models.CharField(blank=True, max_length=255)),
                ("thumbnail_url", models.URLField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["youtube_id"],
            },
        ),
        migrations.CreateModel(
            name="VideoListSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("target", "Target"),
                            ("verification", "Verification"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "retrieved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the external video list state was retrieved.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_snapshots",
                        to="organizer.videolistsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VideoListSnapshotItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("deleted", "Deleted"),
                            ("private", "Private"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "captured_title",
                    models.CharField(
                        blank=True,
                        help_text="Title observed when this snapshot item was captured.",
                        max_length=500,
                    ),
                ),
                (
                    "captured_channel_title",
                    models.CharField(
                        blank=True,
                        help_text="Channel title observed when this snapshot item was captured.",
                        max_length=255,
                    ),
                ),
                (
                    "captured_thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail URL observed when this snapshot item was captured.",
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="organizer.videolistsnapshot",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="list_snapshot_items",
                        to="organizer.video",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "position"),
                        name="unique_position_per_video_list_snapshot",
                    ),
                    models.UniqueConstraint(
                        fields=("snapshot", "video"),
                        name="unique_video_per_video_list_snapshot",
                    ),
                ],
            },
        ),
    ]
